### ISSUE TITLE
Parsing timestamp fails

### ISSUE THREAD

**Issue by TheGroundZero** [Ladicle/tcardgen#32]
Hi

When parsing the following frontmatter

```yaml
---
title: "This is the long title of my blogpost"
linkTitle: "Short blogpost title"
author: TheGroundZero
type: posts
publishdate: "2025-01-21T00:00:00Z01:00"
lastmod: "2025-01-22T00:00:00Z01:00"
summary: Blog post for testing tcardgen
comments: false
categories: ["General"]
tags: ["Automation","cover", "Golang"]
series: "Test blog posts"
params:
  images:
    - cover.png
draft: false
---
```

using this command:

```sh
tcardgen -f assets/fonts -t assets/img/card-template.png -o content/blog/general/test/cover.png content/blog/general/test/index.md
```

I encounter the following error:

```
Load fonts from "assets/fonts"
Load template from "assets/img/card-template.png" directory
Failed to generate twitter card for content/blog/general/test/cover.png: parsing time "2025-01-21T00:00:00Z01:00": extra text: "01:00"
2025/01/29 09:44:14 failed to generate 1 twitter cards
```

I need to remove the timezone `01:00` (but keep the `Z`!) from lastmod to fix this.
Removing the `Z` also gives an error:
```
Failed to generate twitter card for content/blog/general/test/cover.png: parsing time "2025-01-22T00:00:00" as "2006-01-02T15:04:05Z07:00": cannot parse "" as "Z07:00"
```

Why is there a difference in parsing pubdate and lastmod?
Could the timestamp format be made configurable, as I usually use `2006-01-02` format for manually entered pubdate/lastmod?
