### ISSUE TITLE
Configuring standard author

### ISSUE THREAD

**Issue by ress997** [Ladicle/tcardgen#7]
I want to set the standard author information from the configuration file.

 ```yaml
author:
  - name: foo
```

**Comment by ress997** [comment]
It would also be great if you could set the author's icon from the configuration file.
```yaml
author:
  - name: foo
    icon: author.png
```
